// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Text     string `json:"text"`
	ParentID string `json:"parentID"`
	PostID   string `json:"postID"`
}

type Mutation struct {
}

type Post struct {
	ID       string     `json:"id"`
	Username string     `json:"username"`
	Title    string     `json:"title"`
	Text     string     `json:"text"`
	Comments []*Comment `json:"comments"`
}

type Query struct {
}
